### YamlMime:UniversalReference
ms.openlocfilehash: 777051058935475aebf2055932882ec0cd21fea9
ms.sourcegitcommit: efa2d98deffe8a0d41a8d63f9f07aa720862e6ab
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 12/13/2018
ms.locfileid: "52135175"
items:
- uid: azure-servicefabric.TestErrorChaosEvent
  name: TestErrorChaosEvent
  fullName: TestErrorChaosEvent
  children:
  - azure-servicefabric.TestErrorChaosEvent.reason
  langs:
  - typeScript
  type: interface
  summary: >-
    <span data-ttu-id="992ca-101">Beschreibt ein Chaos-Ereignis, das generiert wird, tritt ein unerwartetes Ereignis in der Chaos-Engine.</span><span class="sxs-lookup"><span data-stu-id="992ca-101">Describes a Chaos event that gets generated when an unexpected event occurs in the Chaos engine.</span></span>

    <span data-ttu-id="992ca-102">Chaos gefunden aufgrund der Momentaufnahme des Clusters inkonsistent, während eine Entität Fehler, z. B., dass die Entität bereits fehlerhaft wurde – Was wäre ein unerwartetes Ereignis.</span><span class="sxs-lookup"><span data-stu-id="992ca-102">For example, due to the cluster snapshot being inconsistent, while faulting an entity, Chaos found that the entity was already faulted -- which would be an unexpected event.</span></span>
  extends:
    name: azure-servicefabric.ChaosEvent
  package: azure-servicefabric
- uid: azure-servicefabric.TestErrorChaosEvent.reason
  name: reason
  fullName: reason
  children: []
  langs:
  - typeScript
  type: property
  summary: <span data-ttu-id="992ca-103">Beschreibt, warum TestErrorChaosEvent generiert wurde.</span><span class="sxs-lookup"><span data-stu-id="992ca-103">Describes why TestErrorChaosEvent was generated.</span></span> <span data-ttu-id="992ca-104">Chaos wird beispielsweise versucht, eine Partition einen Fehler, aber feststellt, dass die Partition nicht mehr an Fehlertoleranz zu erzielen ist, und klicken Sie dann eine TestErrorEvent generiert wird, mit dem Grund an, die besagt, dass die Partition nicht fehlertolerant ist.</span><span class="sxs-lookup"><span data-stu-id="992ca-104">For example, Chaos tries to fault a partition but finds that the partition is no longer fault tolerant, then a TestErrorEvent gets generated with the reason stating that the partition is not fault tolerant.</span></span>
  optional: true
  syntax:
    content: 'reason?: string'
    return:
      type:
      - string
  package: azure-servicefabric
references:
- uid: azure-servicefabric.ChaosEvent
  name: ChaosEvent
  spec.typeScript:
  - name: ChaosEvent
    fullName: ChaosEvent
    uid: azure-servicefabric.ChaosEvent
